Creacion por defecto de cola test

diff --git a/jteller/templates/configmaps/rabbitmq-queue.yaml b/jteller/templates/configmaps/rabbitmq-queue.yaml
--- a/jteller/templates/configmaps/rabbitmq-queue.yaml
+++ b/jteller/templates/configmaps/rabbitmq-queue.yaml
@@ -7,12 +7,26 @@ data:
   create.sh: |
     #!/bin/sh
 
-    # Wait for RabbitMQ to be ready
-    while ! curl -u {{.Values.environment.backend.rabbitmq.username |  b64dec}}:{{.Values.environment.backend.rabbitmq.password |  b64dec}} -sf http://localhost:15672/api/aliveness-test/%2f; do
-      echo "waiting for rabbitmq"
-      sleep 2
-    done
+    # Define a function to create the queue
+    create_queue() {
+      while ! curl -u {{.Values.environment.backend.rabbitmq.username |  b64dec}}:{{.Values.environment.backend.rabbitmq.password |  b64dec}} -sf http://localhost:15672/api/aliveness-test/%2f; do
+        echo "waiting for rabbitmq"
+        sleep 2
+      done
 
-    # Create the queue
-    curl -u {{.Values.environment.backend.rabbitmq.username |  b64dec}}:{{.Values.environment.backend.rabbitmq.password |  b64dec}} -XPUT -H 'content-type:application/json' -d '{"auto_delete":false,"durable":true}' http://localhost:15672/api/queues/%2f/{{.Values.environment.backend.rabbitmq.queue}}
+      # Try to create the queue and capture the response code
+      RESPONSE=$(curl -u {{.Values.environment.backend.rabbitmq.username |  b64dec}}:{{.Values.environment.backend.rabbitmq.password |  b64dec}} -XPUT -H 'content-type:application/json' -d '{"auto_delete":false,"durable":true}' http://localhost:15672/api/queues/%2f/my-queue -w "%{http_code}" -o /dev/null)
 
+      if [ "$RESPONSE" -ne 201 ] && [ "$RESPONSE" -ne 204 ]; then
+        echo "Failed to create queue, response code: $RESPONSE"
+        return 1
+      else
+        echo "Queue created successfully"
+        return 0
+      fi
+    }
+
+    # Attempt to create the queue
+    if ! create_queue; then
+      echo "PostStart Hook: queue creation failed but not stopping the container"
+    fi
